language: objective-c

branches:
     only:
          - master

     xcode_project: BlackfootDictionary.xcodeproj
     xcode_scheme: BlackfootDictionaryTests
     osx_image: xcode6.4
     xcode_sdk: iphonesimulator8.4 

     script:
         - xcodebuild clean build test -project BlackfootDictionary.xcodeproj -scheme BlackfootDictionaryTests
